language: python

services:
  - docker

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true


# command to install dependencies
before_install:
  - pip install -U pip wheel
  - pip install -r requirements.txt
  - pip install codecov
  - pip install pytest-cov

install:
  - pip install .
# command to run tests
script:
  - pytest
  - codecov

deploy:
  provider: pypi
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  on:
    tags: true
  distributions: "sdist bdist_wheel"
  skip_existing: true
